exclude: '^$'
fail_fast: false
default_stages: [commit, push]
default_language_version:
    python: python3.6
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0  # Use the ref you want to point at
    hooks:
    -   id: flake8
    -   id: detect-private-key # checks for the existence of private keys
    -   id: detect-aws-credentials # checks for the existence of AWS secrets that you have set up with the AWS CLI
        args: ['--allow-missing-credentials']
    -   id: no-commit-to-branch
        args: [--branch, master] # master is the default if no args are set
    # -   id: trailing-whitespace
    # -   id: check-added-large-files # prevent giant files from being committed
    #     args: ['--maxkb=123']
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.670
    hooks:
    -   id: mypy
        args: [--ignore-missing-imports]
-   repo: git@github.com:Yelp/detect-secrets
    rev: v0.12.0
    hooks:
    -   id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
        exclude: .*/tests/.*
